import EXAM_INVALID from './EXAM_INVALID';
import EXAM_NOT_EXIST from './EXAM_NOT_EXIST';
import NEED_ALL_QUESTION_MARKED from './NEED_ALL_QUESTION_MARKED';
import EXAM_GOTO_THIRD_PARTY from './EXAM_GOTO_THIRD_PARTY';

export default {
    EXAM_INVALID,
    EXAM_NOT_EXIST,
    NEED_ALL_QUESTION_MARKED,
    EXAM_GOTO_THIRD_PARTY
}